repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: pretty-format-json
        name: Format JSON
        args: ["--autofix", "--indent=2", "--no-ensure-ascii"]
        files: ^app/data/.*\.json$
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.2.5"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.13.0
    hooks:
      - id: eslint
  - repo: local
    hooks:
      - id: validate-data
        name: Walidacja / Validation
        entry: python scripts/validate_data.py
        language: system
        files: ^app/data/(products|recipes)\.json$
      - id: check-alias-conflicts
        name: Check alias conflicts
        entry: python scripts/check_alias_conflicts.py
        language: system
        files: ^app/data/products\.json$
        pass_filenames: false
