ci:
  autofix_prs: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: pretty-format-json
        name: Format JSON (non-data)
        args: ["--autofix", "--no-sort-keys", "--indent", "2"]
        files: "^(app/static/translations/|app/schemas/|app/config/).+\\.json$"
        exclude: "^app/data/.+\\.json$"
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: "\\.(js|ts|jsx|tsx|css|scss|html|md|markdown|yml|yaml)$"
        exclude: "^app/data/.+\\.json$"
        additional_dependencies: ["prettier@3.0.3"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.13.0
    hooks:
      - id: eslint
        additional_dependencies:
          - "@eslint/js@9.13.0"
          - "eslint-plugin-prettier@5.1.3"
          - "eslint-config-prettier@9.0.0"
          - "prettier@3.0.3"
