name: Validation

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: -a
      - name: Validate data
        run: python scripts/validate_data.py
      - name: Check alias conflicts
        run: python scripts/check_alias_conflicts.py
