name: Validation

on:
  push:
    paths:
      - 'app/data/**/*.json'
      - 'scripts/validate_data.py'
      - 'scripts/check_alias_conflicts.py'
      - '.pre-commit-config.yaml'
      - '.github/workflows/validation.yml'
  pull_request:
    paths:
      - 'app/data/**/*.json'
      - 'scripts/validate_data.py'
      - 'scripts/check_alias_conflicts.py'
      - '.pre-commit-config.yaml'
      - '.github/workflows/validation.yml'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Walidacja / Validation
        run: pre-commit run -a || (git status --porcelain && git --no-pager diff && exit 1)
